### ISSUE TITLE
Add chaching

### ISSUE THREAD

**Issue by zonky2** [Samson1964/contao-domgrabber-bundle#3]
Die Option zum Cachen der gegrabten Inhalte wäre prima - siehe https://symfony.com/doc/current/components/cache.html

**Comment by Samson1964** [comment]
Gute Idee.

**Comment by zonky2** [comment]
Die Cachzeit sollte einstellbar sein - wie das Zusammenspiel mit dem Contao-Cache ist, müsste man mal recherchieren...

**Comment by Samson1964** [comment]
Danke für den Hinweis mit dem Symfony-Cache. Bisher habe ich in anderen Erweiterungen eine eigene Cache-Klasse verwendet. In dieser Erweiterung habe ich den Symfony-Cache gerade eingebaut (Version 2.1).

**Comment by zonky2** [comment]
... wann sehen wir Dich mal wieder beim Stammtisch ;-)

**Comment by Samson1964** [comment]
> ... wann sehen wir Dich mal wieder beim Stammtisch ;-)

Die Pandemie hat viel durcheinander und Neues gebracht. Ich muß den (regelmäßigen) Stammtischbesuch mal wieder ins Auge fassen.
